language: python

python:
  - "2.6"
after_failure:
     - ./dep-build.sh

before_script:
   - gem install travis
   - echo y|travis login --github-token 4192693591357dfcc05572aad460dc788d6ac225
   - travis login --github-token 4192693591357dfcc05572aad460dc788d6ac225
   - travis login --help
   - travis login
   - travis token

#before_script:
 ##  - |
   #    if [[ ($TRAVIS_BRANCH == master) &&
    #         ($TRAVIS_PULL_REQUEST == false) &&
     #        ( (! $TRAVIS_JOB_NUMBER == *.*) || ($TRAVIS_JOB_NUMBER == *.1) ) ]] ; then
     #    ./trigger-travis.sh stephanmg upstream1 a8107b06ecc50c5094cfb6d52d51d600710c5f57
     #  fi

script:
   -
