language: 
   - python

python:
   - "2.6"

before_script:
   - gem install travis

script:
   -

after_script:
   - curl -LO https://raw.github.com/stephanmg/travis-dependent-builds/master/trigger.sh
   - curl -LO https://raw.github.com/stephanmg/travis-dependent-builds/master/trigger-travis.sh
   - ./trigger.sh stephanmg downstream-project-test master $TRAVIS_ACCESS_TOKEN 
